#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path('../../../lib', __FILE__)
require 'uninterruptible'

# Simple server, writes back  what it reads
class EchoServer
  include Uninterruptible::Server

  def handle_request(client_socket)
    data_to_echo = client_socket.gets
    client_socket.puts(data_to_echo)
  end
end

require_relative './tls_configuration'
include TLSConfiguration

echo_server = EchoServer.new
echo_server.configure do |config|
  config.start_command = 'spec/support/echo_server'
  config.log_level = Logger::FATAL
  config.allowed_networks = ['127.0.0.1/8', '::1/128']

  if ENV['TLS_ENABLED']
    config.tls_key = tls_key
    config.tls_certificate = tls_certificate
  end
end
echo_server.run
